### ISSUE TITLE
ch2_enabled

### ISSUE THREAD

**Issue by ananyevgv** [khenderick/esphome-opentherm#7]
Add ch2_enabled, for boilers with indirect heating, the inclusion of a second heating circuit is required (Baxi Nuvola-3 b40)

**Comment by khenderick** [comment]
I've added this functionality in [pull request #8](https://github.com/khenderick/esphome-opentherm/pull/8). You can see the required config changes to configure those new sensors etc over there.

Since my boiler doesn't support a second channel, I cannot test whether everything works correct. Please keep me posted if all sensors etc work as expected so I can merge it into the default code.

**Comment by ananyevgv** [comment]
I'll try to check this week.
While I have another code working, with a few of my improvements

**Comment by ananyevgv** [comment]
You can add a few more sensors  //ASFflag error

error code 
Service_required 
Lockout_reset 
Low_water_pressure
Gas_fault	return
Air_fault 
Water_overtemp

**Comment by khenderick** [comment]
I've added these sensors. The comment in the PR is updated describing these sensors.

**Comment by ananyevgv** [comment]
promptly ;-)  I will try to check as quickly as possible

**Comment by ananyevgv** [comment]
It would be nice to add a PID. :-)

I can throw off some interesting links on this topic. I experimented with my boiler for a long time (hot water did not work). I found many different versions of the code.

Some boilers require an exchange
Slave Member ID code
Member ID code
Slave Version
Master Version

**Comment by khenderick** [comment]
I'm not planning to implement any PID related logic, as there are many great PID controllers available, both in Home Assistant and in ESPHome. 

Using for example the [PID Climate](https://esphome.io/components/climate/pid.html) component in ESPHome with its output optionally connected through a [Slow PWM Output](https://esphome.io/components/output/slow_pwm.html) component towards the CH enabled switch could be a great implementation.

The issue here is that there are many different boilers and heating systems, each with their own set of needs and quirks, so I'd have to spend a ton of time re-implementing what's basically already out there, but slightly different. And one of the strengths of HA and/or ESPHome is that by exposing various switches, sensors, ... various components can be hooked together very easy to build what is perfect for you setup. In the mean time, I can focus on making this particular component as good and reliable as possible exposing all the boiler's functionality.

If more sensors could be exposed that would make it easier to integrate this component with others such as the PID climate, please let me know.

**Comment by ananyevgv** [comment]
ok.

MessageID::Toutside, 0));

spied here:
https://github.com/DRazumovskiy/Baxi-Luna3-Comfort-IN-HT-Solar-MQTT/tree/master/baxi-luna3-mqtt

**Comment by khenderick** [comment]
Outside temperature added :+1:

**Comment by ananyevgv** [comment]
MessageID:Status 0
bool OpenTherm::isFlameOn(unsigned long response) {
	return response & 0x8;

**Comment by khenderick** [comment]
> MessageID:Status 0 bool OpenTherm::isFlameOn(unsigned long response) { return response & 0x8;

Not sure whether I understand what you mean. This is already implemented as the `flame_active` binary sensor.

**Comment by ananyevgv** [comment]
I'm sorry I didn't see it

**Comment by ananyevgv** [comment]
Another stupid question, why number and not climate?

**Comment by khenderick** [comment]
Because a climate would give the impression that it would work like any other climate-controlled device. Typically on a climate you'll for example set the room temperature. However, central heating setpoints on a boiler typically control the temperature of the hot water flowing to your floor, radiator, or other heat-exchanger, which is a lot of cases doesn't reflect 1-to-1 to the room temperature. It's similar to the DHW setpoint, this would be set to some safe value (to prevent bacteria growth), and you'd mix the water temperature for your shower with another device; the faucet in this case.

If however, you'd be using some forced air heat exchanger where this setpoint almost exactly controls the temperature of the air coming out of is, you could simply hook it up to one of the climate components in ESPHome.

**Comment by ananyevgv** [comment]
Is it still possible to use PID (Esphome) with your integration? What should I specify in heat_output?

**Comment by khenderick** [comment]
Depends on the climate/pid integration you're using. You could link it up directly to the CH enabled, or go through a slow PWM component. If a switch would not be accepted, you can put a template output in between to map to the switch.

Personally I have multiple climates controlling the same boiler, so I template climates in HA that open/close my central heating hot water valves for the right zones, and have an automation so that if any valve is open, the CH enabled is turned ON.

**Comment by ananyevgv** [comment]
there are plans to do the same..........

**Comment by ananyevgv** [comment]
I'm probably already tired of it
MessageID:17:RelModLevel

**Comment by khenderick** [comment]
Already available.

**Comment by ananyevgv** [comment]
src/opentherm/OpenTherm.cpp: In constructor 'OpenTherm::OpenTherm(int, int, bool)':
src/opentherm/OpenTherm.cpp:14:2: error: class 'OpenTherm' does not have any field named 'Fault'
   14 |  Fault(0),
      |  ^~~~~
src/opentherm/OpenTherm.cpp: At global scope:
src/opentherm/OpenTherm.cpp:443:1: error: expected declaration before '}' token
  443 | }
      | ^

**Comment by khenderick** [comment]
That's probably from another component, as this code has no `OpenTherm.cpp` file, nor an `OpenTherm` class.

**Comment by ananyevgv** [comment]
Yes, the campaign has tightened up from the old project, it is necessary to delete

**Comment by ananyevgv** [comment]
![image](https://github.com/khenderick/esphome-opentherm/assets/81970899/c72ac337-f781-4ac2-acd5-5280a499236f)

**Comment by ananyevgv** [comment]
it works on the test board

**Comment by khenderick** [comment]
Good to hear :+1:.

Based on the screenshot however, it seems your boiler does not support `outside_temperature`, `oem_diagnostic_code`, `ch_2_setpoint_temperature` and `return_temperature`. These all return `UNKNOWN_DATA`. You can remove these from your configuration.

**Comment by khenderick** [comment]
The code is merged in main, you can remove the `@feature/ch2` from this component's source.

**Comment by ananyevgv** [comment]
![IMG_20230621_232014.jpg](https://github.com/khenderick/esphome-opentherm/assets/81970899/029ca087-7254-4db2-9d7f-64bfa5320103)

- 
Test

**Comment by ananyevgv** [comment]
![Screenshot_2023-06-21-23-30-22-053_io.homeassistant.companion.android.jpg](https://github.com/khenderick/esphome-opentherm/assets/81970899/57f70ec6-d265-4a66-96ef-5f975f670c2d)

Boilers
